# Generated by Django 4.0.1 on 2022-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('federal_district', models.CharField(max_length=100)),
                ('region_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('area_type', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('settlement_type', models.CharField(max_length=100)),
                ('settlement', models.CharField(max_length=100)),
                ('kladr_id', models.IntegerField()),
                ('fias_id', models.CharField(max_length=100)),
                ('fias_level', models.IntegerField()),
                ('capital_marker', models.IntegerField()),
                ('okato', models.IntegerField()),
                ('oktmo', models.IntegerField()),
                ('tax_office', models.IntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('geo_lat', models.FloatField()),
                ('geo_lon', models.FloatField()),
                ('population', models.IntegerField()),
                ('foundation_year', models.DateField()),
            ],
        ),
    ]
