# Generated by Django 4.0.1 on 2022-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='foundation_year',
            field=models.CharField(max_length=100),
        ),
    ]
