# Generated by Django 4.0.1 on 2022-02-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmap', '0003_alter_city_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='capital_marker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='fias_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='geo_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='geo_lon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='kladr_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='okato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='oktmo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='tax_office',
            field=models.CharField(max_length=100),
        ),
    ]
